In [1]:
import pandas as pd
import numpy as np

In [9]:
dataset=pd.read_csv("FoodandCalories.csv")

In [10]:
dataset.columns


Index(['Food', 'Serving', 'Calories'], dtype='object')

In [11]:
x=dataset[['Food', 'Serving']]

In [12]:
x

Food              Serving
0                   Artichoke  1 artichoke (128 g)
1                     Arugula         1 leaf (2 g)
2                   Asparagus       1 spear (12 g)
3                   Aubergine  1 aubergine (458 g)
4                    Beetroot        1 beet (82 g)
..                        ...                  ...
557  Wendy’s Jr. Cheeseburger     1 burger (129 g)
558  Wendy’s Son of Baconator     1 burger (218 g)
559                   Whopper     1 burger (291 g)
560                    Zinger   1 sandwich (202 g)
561             Zinger Burger   1 sandwich (202 g)

[562 rows x 2 columns]

In [20]:
from sklearn.preprocessing  import LabelEncoder

In [21]:
food_label=LabelEncoder()

In [22]:
food=x['Food']

In [23]:
serving=x['Serving']

In [24]:
food_labeled=food_label.fit_transform(food)

In [26]:
food_labeled

array([ 14,  15,  17,  18,  41,  42,  47,  56,  60,  76,  85,  86,  91,
        92,  94, 100, 123, 126, 127, 137, 139, 148, 159, 162, 185, 187,
       192, 211, 212, 218, 222, 223, 224, 238, 250, 254, 255, 260, 263,
       319, 321, 330, 333, 335, 336, 350, 358, 362, 383, 391, 397, 403,
       414, 430, 456, 463, 475, 484, 496, 497, 513, 532, 537,   0,   5,
         6,   7,  19,  30,  50,  51,  52,  80,  99, 132, 151, 164, 165,
       169, 194, 208, 221, 225, 230, 247, 249, 253, 261, 264, 270, 281,
       282, 312, 316, 326, 335, 339, 348, 351, 353, 356, 364, 366, 368,
       376, 377, 379, 395, 398, 399, 401, 406, 465, 466, 478, 480, 514,
        27,  28,  29,  24,  40,  46,  48,  49,  25,  59,  73,  74, 539,
       104, 106, 108, 112, 115, 119, 124, 125, 133, 137, 140, 143, 146,
       167, 171, 172, 175, 186, 188, 197, 205, 206, 226, 232, 241, 248,
       252, 258, 271, 273, 288, 302, 305, 323, 340, 344, 345, 349, 352,
       354, 359, 365, 370, 382, 384, 390, 400, 402, 405, 409, 41

In [27]:
serving_labeled=food_label.fit_transform(serving)

In [28]:
serving_labeled

array([  3, 151, 329,   4,  10, 192, 175,  16, 330, 141, 191,  39, 128,
       334, 153,  43, 138, 140, 348, 118,  71,  50,  86,  53, 124, 137,
        13,  46, 132, 133,  56, 175, 134, 345, 117, 148, 149, 154, 139,
       172, 116, 292, 208, 175, 176, 185, 115, 193, 212, 215, 217, 152,
       230, 291,  15, 332, 211, 349, 354, 353, 228, 333, 362, 179,   1,
        98,   2,   5,   6,  65, 269,  67, 358,  42,  45,  54,  57, 119,
       121, 127, 101,  69, 130, 136,  69, 179, 157, 155, 156, 159, 163,
       164, 171,  64, 173, 175, 177, 131, 187, 189, 190, 129,  11, 205,
       206, 207, 209, 216,  66, 218,  62, 335, 336,  70, 342, 343, 357,
       268, 274, 105, 219,  85, 106, 214, 363, 145,  80,  36, 351, 226,
       232, 338, 277, 201, 196, 279, 104, 144, 288, 109, 143,  37, 197,
       366, 368, 199, 287, 125, 280, 282, 285, 294, 237, 239,  98, 102,
       146, 275, 273, 273,  87, 194, 158,  12, 270, 102, 370, 184, 104,
       257, 367, 236, 295,  44, 371, 251, 182, 380, 254, 313, 30

In [35]:
food_labeled_shaped=food_labeled.reshape(-1,1)

In [37]:
food_labeled_shaped.shape

(562, 1)

In [38]:
serving_labeled_shaped=serving_labeled.reshape(-1,1)

In [39]:
serving_labeled_shaped.shape

(562, 1)

In [40]:
x_labeled=np.hstack([food_labeled_shaped,serving_labeled_shaped])

In [42]:
x_labeled

array([[ 14,   3],
       [ 15, 151],
       [ 17, 329],
       ...,
       [531,  31],
       [534, 243],
       [535, 243]])

In [43]:
x_labeled.shape

(562, 2)

In [44]:
y=dataset['Calories']

In [45]:
y

0       60
1        1
2        2
3      115
4       35
      ... 
557    290
558    700
559    672
560    517
561    517
Name: Calories, Length: 562, dtype: int64

In [15]:
""""  y_no=[]
for i in y:
    for j in {i}:
        #if (j=='c' or j=='a' or j=='l' or j==' '):
         if (j>=48 and j<=57):
                no=j;
      
         y_no=no;
            """

'"  y_no=[]\nfor i in y:\n    for j in {i}:\n        #if (j==\'c\' or j==\'a\' or j==\'l\' or j==\' \'):\n         if (j>=48 and j<=57):\n                no=j;\n      \n         y_no=no;\n            '

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
model=LinearRegression()

In [48]:
model.fit(x_labeled,y)

LinearRegression()

In [50]:
model.predict['Mango','1 mango (336 g)']

TypeError: 'method' object is not subscriptable